apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t1kizbfq6-nodejs
  janus-idp.io/tekton: t1kizbfq6-nodejs
  backstage.io/kubernetes-id: t1kizbfq6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t1kizbfq6-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
